---
name: example-deployment

releases:
  - { name: example-bosh-release, version: latest }
  - { name: bpm, version: latest }

stemcells:
  - alias: bosh-google-kvm-ubuntu-xenial-go_agent
    os: ubuntu-xenial
    version: latest

update:
  canaries: 1
  max_in_flight: 3
  canary_watch_time: 15000-30000
  update_watch_time: 15000-300000

instance_groups:
  - name: go_app
    instances: 1
    azs: [ us-central1-c ]
    jobs:
      - name: app_job
        release: example-bosh-release
        properties:
          app:
            response_body: "This response body came from the manifest"
      - name: bpm
        release: bpm
    vm_type: micro
    stemcell: bosh-google-kvm-ubuntu-xenial-go_agent
    networks:
      - name: quicksilver
